flow_start_time: "2023-08-04T17:20:00+00:00" # time travel for testing or reprocessing
                # use ISO8601 format: if UTC use +00:00 or Z

source:
  mode: git
  git:
    url: https://github.com/echostack-org/echodataflow.git
    branch: origin/drixo16_2026

default_work_pool_name: local
flows:
  # copy_raw:
  #   module: flows_helper
  #   deployment_name: copy_raw
  #   interval: 2
  raw2Sv:
    module: flows_acoustics
    deployment_name: raw2Sv
    interval: 5
  create_MVBS:
    module: flows_acoustics
    deployment_name: create-MVBS
    interval: 10
    cron_offset: 3
    inject_time_offset: true
  predict_hake:
    module: flows_acoustics
    deployment_name: predict-hake
    interval: 20
    inject_time_offset: true
  file_upload_acoustics:
    module: flows_helper
    deployment_name: file-upload-acoustics
    flow_alias: file_upload
    interval: 10
    apply_separately: true
    work_pool_name: local
  # file_upload_trawl:
  #   module: flows_helper
  #   deployment_name: file-upload-trawl_20250902
  #   flow_alias: file_upload
  #   interval: 10
  #   cron_offset: 3
  #   apply_separately: true
  #   work_pool_name: local
